### ISSUE TITLE
Error when using the GUI

### ISSUE THREAD

**Issue by joaorsbarbosa** [PoyBoi/StableDiffusionHelper#4]
After having to install packages manually and re-installing dlib, I managed to get GUI.bat to run but then as soon as I pressed any buttons I'd get hit with:

```
--------
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\dependencies\utils.py", line 658, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\dependencies\utils.py", line 883, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 658, in get_cached_model_fields
    return get_model_fields(model)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
    return [
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "D:\Downloads\Auto Crop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

**Comment by PoyBoi** [comment]
Hey, thanks for opening an issue, happy to help !!

1. Why did you have to install the dependencies manually ? The code is made for it to run within a venv (virtual environment) and it has all the needed libraries to run.
2. Did you install those libraries in the venv ?
3. Was the Gradio GUI opening for you ?

**Comment by joaorsbarbosa** [comment]
1. The GUI.bat was failing to load, and throwing errors about missing packages.
2. Yes. I made sure that they were installed in the venv, using the versions in the requirements.txt
3. It is opening, but if I touch any button I get the error above.

I deleted the folder and ran the install.bat again to make sure I hadn't screw anything up, but with a clean install I set get this issue
Latest still is:

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\dependencies\utils.py", line 658, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\dependencies\utils.py", line 883, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 658, in get_cached_model_fields
    return get_model_fields(model)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
    return [
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "C:\AutoCrop\StableDiffusionHelper\venv_sdh\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
`

**Comment by PoyBoi** [comment]
I think I have found the issue, I'll have to re-write the GUI.bat, and maybe add a little verbosity to the handling of errors, as well as showing what's being downloaded during the init set-up

**Comment by PoyBoi** [comment]
Until then. can you try getting these specific versions in the venv ?
```
pydantic == 2.8.0
fastapi == 0.111.0
starlette == 0.37.2
```

**Comment by joaorsbarbosa** [comment]
Am now, however, getting errors with the suitability check

`ValueError: An event handler (launch_confirm) didn't receive enough output values (needed: 3, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x00000123B5F4A6B0>, <gradio.components.button.Button object at 0x00000123B5F4A710>, <gradio.components.textbox.Textbox object at 0x00000123B5F4A7D0>]
Received outputs:
    ["Processing Status: ⭕ ERROR ⭕: Cause:

🔧expected str, bytes or os.PathLike object, not NoneType🔧"]
`

**Comment by PoyBoi** [comment]
Can you send me a screenshot of the settings you're running SC on ? Feel free to blur out any things you want to hide (try to get all of the fields in the SS if possible)

**Comment by PoyBoi** [comment]
> Until then. can you try getting these specific versions in the venv ?
> 
> ```
> pydantic == 2.8.0
> fastapi == 0.111.0
> starlette == 0.37.2
> ```

I have updated these in the new requirements.txt as well, so I doubt you will have to go through these steps in a future install

**Comment by joaorsbarbosa** [comment]
Apologies for the delay. 
I haven't used it in a few days, but I did managed to get it to work. But it was odd. Sometimes with the same exact settings it would fail, other times it would work, just had to restart the process. But I did find that lowering the detection thresholds helped. Although it would mean that sometimes it would "detect" things that were no there. 
Sorry for not being able to provide more details!

**Comment by PoyBoi** [comment]
> Apologies for the delay. I haven't used it in a few days, but I did managed to get it to work. But it was odd. Sometimes with the same exact settings it would fail, other times it would work, just had to restart the process. But I did find that lowering the detection thresholds helped. Although it would mean that sometimes it would "detect" things that were no there. Sorry for not being able to provide more details!

That's really weird, this issue should not be happening (didn't happen to me when I was stress testing this), it could be a Gradio issue, I'll look at this in a bit, as this is not a "asap" fix. 

And about the detection algo isn't the best at lower thresholds, as it lowers the "confidence" of the objects it considers a "face" for detection, so that's why you're getting non-existent detections.

If any new issues should arise (I hope not) feel free to re-open this issue !!

**Comment by joaorsbarbosa** [comment]
Sure! In the meantime I completely deleted and reinstalled with the new requirements from the start, and as long as I run the gui.bat in admin, it runs well!

**Comment by PoyBoi** [comment]
> Sure! In the meantime I completely deleted and reinstalled with the new requirements from the start, and as long as I run the gui.bat in admin, it runs well!

Glad to hear that, cheers !
